server:
  port: 8882
spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/sca-auth?characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  servlet:
    profiles:
      active: pro
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
    profiles:
      active: pro
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
      default-property-inclusion: non-null
      serialization:
        indent-output: true
        fail-on-empty-beans: false
      deserialization:
        fail-on-unknown-properties: false
      parser:
        allow-unquoted-control-chars: true
        allow-single-quotes: true
logging:
  level:
    root: info
  path: C:/LOGS/SpringCloudAdmin/auth/