logging:
  path: C:/LOGS/SpringCloudAdmin/
  level:
    root: debug
eureka:
  client:
    service-url:
      defautZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    open-in-view: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: pro
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non-null
    serialization:
      indent-output: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
    parser:
      allow-unquoted-control-chars: true
      allow-single-quotes: true
