server:
  port: 8880
spring:
  profiles:
    include: common
  application:
    name: system-server
  datasource:
    url: jdbc:mysql://localhost:3306/sca-system?characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456