server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetchRegistry: false
spring:
  application:
    name: eureka-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/sca-eureka?characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
  profiles:
    active: pro
logging:
  path: C:/LOGS/SpringCloudAdmin/eruka
  level:
    root: info